//! End-to-end tests for output ownership (spec 0001), run against a temporary Dart package.

use flint_build::builder::{BuildReport, build, clean};
use flint_build::config::Pubspec;
use flint_build::generators::flint_json::emitter::FlintJsonGenerator;
use flint_build::output;
use flint_build::registry::PluginRegistry;
use std::fs;
use std::path::PathBuf;
use std::time::{Duration, SystemTime};
use tempfile::TempDir;

const USER: &str = "part 'user.g.dart';

@JsonSerializable()
class User {
  final int id;
  User({required this.id});
}
";

const FOREIGN: &str = "// GENERATED CODE - DO NOT MODIFY BY HAND\n\npart of 'x.dart';\n\n// written by another generator\n";

struct Package {
    dir: TempDir,
}

impl Package {
    fn new(flint_yaml: &str) -> Self {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir(dir.path().join("lib")).unwrap();
        fs::write(dir.path().join("flint.yaml"), flint_yaml).unwrap();
        Package { dir }
    }

    fn json() -> Self {
        Self::new("plugins:\n  flint_json:\n")
    }

    fn path(&self, relative: &str) -> PathBuf {
        self.dir.path().join(relative)
    }

    fn write(&self, relative: &str, content: &str) {
        fs::write(self.path(relative), content).unwrap();
    }

    fn read(&self, relative: &str) -> String {
        fs::read_to_string(self.path(relative)).unwrap()
    }

    fn exists(&self, relative: &str) -> bool {
        self.path(relative).exists()
    }

    fn set_mtime(&self, relative: &str, seconds_after_epoch: u64) {
        let file = fs::File::options()
            .write(true)
            .open(self.path(relative))
            .unwrap();
        file.set_modified(SystemTime::UNIX_EPOCH + Duration::from_secs(seconds_after_epoch))
            .unwrap();
    }

    /// Makes an output look older than its source, so the mtime check can't skip it.
    fn age(&self, relative: &str) {
        self.set_mtime(relative, 1);
    }

    fn build(&self, force: bool) -> BuildReport {
        let mut registry = PluginRegistry::new();
        registry.register("flint_json", Box::new(FlintJsonGenerator));
        let pubspec = Pubspec::from_str("name: app\n").unwrap();
        build(self.dir.path(), &pubspec, force, &registry).unwrap()
    }
}

#[test]
fn test_writes_owned_output_for_annotated_source() {
    let package = Package::json();
    package.write("lib/user.dart", USER);

    let report = package.build(false);

    assert_eq!(report.written, vec![package.path("lib/user.g.dart")]);
    assert!(report.errors.is_empty() && report.warnings.is_empty());
    let generated = package.read("lib/user.g.dart");
    assert!(generated.contains("part of 'user.dart';"));
    assert!(generated.contains("_$UserFromJson"));
    assert!(output::is_owned(&package.path("lib/user.g.dart")).unwrap());
}

#[test]
fn test_clean_leaves_files_flint_did_not_write() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.build(false);
    package.write("lib/other.g.dart", FOREIGN);

    let report = clean(package.dir.path()).unwrap();

    assert_eq!(report.deleted, vec![package.path("lib/user.g.dart")]);
    assert_eq!(report.skipped, vec![package.path("lib/other.g.dart")]);
    assert!(!package.exists("lib/user.g.dart"));
    assert_eq!(package.read("lib/other.g.dart"), FOREIGN);
}

#[test]
fn test_unannotated_source_produces_nothing() {
    let package = Package::json();
    package.write(
        "lib/plain.dart",
        "class Plain {\n  final int a;\n  Plain(this.a);\n}\n",
    );
    package.write("lib/color.dart", "enum Color { red, green }\n");

    let report = package.build(false);

    assert!(report.written.is_empty());
    assert!(!package.exists("lib/plain.g.dart"));
    assert!(!package.exists("lib/color.g.dart"));
}

#[test]
fn test_missing_part_directive_warns_and_writes_nothing() {
    let package = Package::json();
    package.write("lib/user.dart", &USER.replace("part 'user.g.dart';\n", ""));

    let report = package.build(false);

    assert!(!package.exists("lib/user.g.dart"));
    assert_eq!(report.warnings.len(), 1);
    assert!(report.warnings[0].contains("part 'user.g.dart';"));
}

#[test]
fn test_unowned_output_is_only_overwritten_with_force() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.write("lib/user.g.dart", FOREIGN);

    let report = package.build(false);
    assert_eq!(report.errors.len(), 1);
    assert!(report.errors[0].contains("wasn't generated by Flint"));
    assert_eq!(package.read("lib/user.g.dart"), FOREIGN);

    let report = package.build(true);
    assert!(report.errors.is_empty());
    assert!(package.read("lib/user.g.dart").contains("_$UserFromJson"));
}

#[test]
fn test_legacy_flint_output_is_treated_as_owned() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.write(
        "lib/user.g.dart",
        "// GENERATED CODE - DO NOT MODIFY BY HAND\n\npart of 'user.dart';\n\n// JsonSerializableGenerator (Powered by Flint)\n",
    );
    package.age("lib/user.g.dart");

    let report = package.build(false);

    assert!(report.errors.is_empty());
    assert_eq!(report.written.len(), 1);
}

#[test]
fn test_plugins_share_one_file_in_config_order() {
    let package = Package::new(
        "plugins:\n  describe:\n    class_annotations: [\"@JsonSerializable\"]\n    template_path: describe.tera\n  flint_json:\n",
    );
    package.write(
        "describe.tera",
        "// GENERATED CODE - DO NOT MODIFY BY HAND\n\npart of '{{ filename }}';\n\n{% for class in classes %}// describes {{ class.name }}\n{% endfor %}",
    );
    package.write("lib/user.dart", USER);

    package.build(false);
    let first = package.read("lib/user.g.dart");
    for _ in 0..10 {
        package.build(true);
        assert_eq!(package.read("lib/user.g.dart"), first);
    }

    let describe = first.find("// describes User").unwrap();
    let json = first.find("_$UserFromJson").unwrap();
    assert!(describe < json, "sections must follow flint.yaml order");
    assert_eq!(first.matches("part of 'user.dart';").count(), 1);
    assert_eq!(first.matches("DO NOT MODIFY BY HAND").count(), 1);
}

#[test]
fn test_stale_owned_output_is_deleted() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.write("lib/gone.dart", &USER.replace("user.g.dart", "gone.g.dart"));
    package.build(false);
    package.write("lib/other.g.dart", FOREIGN);

    package.write("lib/user.dart", "part 'user.g.dart';\n\nclass User {}\n");
    package.age("lib/user.g.dart");
    fs::remove_file(package.path("lib/gone.dart")).unwrap();
    let report = package.build(false);

    assert_eq!(
        report.deleted,
        vec![
            package.path("lib/user.g.dart"),
            package.path("lib/gone.g.dart")
        ]
    );
    assert!(!package.exists("lib/user.g.dart"));
    assert!(!package.exists("lib/gone.g.dart"));
    assert!(package.exists("lib/other.g.dart"));
}

#[test]
fn test_unchanged_output_is_not_rewritten() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.build(false);

    let report = package.build(false);
    assert_eq!(report.up_to_date, 1);

    let report = package.build(true);
    assert_eq!(report.unchanged, 1);
    assert!(report.written.is_empty());
}

#[test]
fn test_config_change_regenerates_and_drops_removed_plugin() {
    let package = Package::new(
        "plugins:\n  flint_json:\n  describe:\n    class_annotations: [\"@JsonSerializable\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for class in classes %}// describes {{ class.name }}\n{% endfor %}",
    );
    package.write("lib/user.dart", USER);
    package.build(false);
    assert!(
        package
            .read("lib/user.g.dart")
            .contains("// describes User")
    );

    // Only flint.yaml is newer than the output; the source is older.
    package.write("flint.yaml", "plugins:\n  flint_json:\n");
    package.set_mtime("lib/user.dart", 1);
    package.set_mtime("lib/user.g.dart", 2);
    let report = package.build(false);

    assert_eq!(report.written, vec![package.path("lib/user.g.dart")]);
    let generated = package.read("lib/user.g.dart");
    assert!(!generated.contains("// describes User"));
    assert!(generated.contains("_$UserFromJson"));
}

#[test]
fn test_unchanged_output_gets_fresh_mtime_so_next_build_skips_it() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.build(false);
    package.age("lib/user.g.dart");

    let report = package.build(false);
    assert_eq!(report.unchanged, 1);

    let report = package.build(false);
    assert_eq!(report.up_to_date, 1);
}

#[test]
fn test_template_copied_from_old_builtin_gets_one_part_of() {
    let package = Package::new("plugins:\n  flint_json:\n    template_path: old.tera\n");
    package.write(
        "old.tera",
        "// GENERATED CODE - DO NOT MODIFY BY HAND\n// ignore_for_file: unnecessary_cast\n\npart of '{{ filename }}';\n\n{% for class in classes %}// {{ class.name }}\n{% endfor %}",
    );
    package.write("lib/user.dart", USER);

    package.build(false);

    let generated = package.read("lib/user.g.dart");
    assert_eq!(generated.matches("part of ").count(), 1);
    assert_eq!(generated.matches("DO NOT MODIFY BY HAND").count(), 1);
    assert!(generated.contains("// ignore_for_file: unnecessary_cast"));
}

fn package_with_template(template: Option<&str>) -> Package {
    let package = Package::new(
        "plugins:\n  flint_json:\n  custom:\n    class_annotations: [\"@JsonSerializable\"]\n    template_path: custom.tera\n",
    );
    if let Some(template) = template {
        package.write("custom.tera", template);
    }
    package.write("lib/user.dart", USER);
    package
}

#[test]
fn test_missing_template_is_an_error_and_other_plugins_still_run() {
    let package = Package::new(
        "plugins:\n  flint_json:\n  custom:\n    class_annotations: [\"@Describe\"]\n    template_path: custom.tera\n",
    );
    package.write("lib/user.dart", USER);
    package.write(
        "lib/described.dart",
        "part 'described.g.dart';\n\n@Describe()\nclass Described {}\n",
    );

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.errors[0].contains("Plugin 'custom'"));
    assert!(report.errors[0].contains("custom.tera"));
    // Files the broken plugin doesn't match are built as usual; the ones it matches are left alone.
    assert!(package.read("lib/user.g.dart").contains("_$UserFromJson"));
    assert!(!package.exists("lib/described.g.dart"));
    assert_eq!(report.blocked, 1);
}

#[test]
fn test_template_syntax_error_explains_where() {
    let package = package_with_template(Some("{% for c in classes %}{{ c.name }\n"));

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.errors[0].contains("Plugin 'custom'"));
    assert!(report.errors[0].contains("1:"), "{}", report.errors[0]);
}

#[test]
fn test_template_render_error_is_reported_per_file() {
    let package = package_with_template(Some("{{ nope }}\n"));

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.errors[0].contains("user.dart"));
    assert!(report.errors[0].contains("nope"), "{}", report.errors[0]);
    assert!(!package.exists("lib/user.g.dart"));
}

#[test]
fn test_broken_template_leaves_its_outputs_untouched() {
    let package = Package::new(
        "plugins:\n  flint_json:\n  describe:\n    class_annotations: [\"@Describe\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for class in classes %}// describes {{ class.name }}\n{% endfor %}",
    );
    // Only the describe plugin matches only.dart; both plugins match shared.dart.
    package.write(
        "lib/only.dart",
        "part 'only.g.dart';\n\n@Describe()\nclass Only {}\n",
    );
    package.write(
        "lib/shared.dart",
        &format!(
            "{}\n@Describe()\nclass Extra {{}}\n",
            USER.replace("user.g.dart", "shared.g.dart")
        ),
    );
    package.build(false);
    let only = package.read("lib/only.g.dart");
    let shared = package.read("lib/shared.g.dart");
    assert!(shared.contains("// describes Extra") && shared.contains("_$UserFromJson"));

    // A typo in the template while the sources are being edited: nothing the plugin touches may change.
    package.write(
        "describe.tera",
        "{% for class in classes %}{{ class.name }\n",
    );
    package.age("lib/only.g.dart");
    package.age("lib/shared.g.dart");
    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.deleted.is_empty(), "{:?}", report.deleted);
    assert_eq!(report.blocked, 2);
    assert_eq!(package.read("lib/only.g.dart"), only);
    assert_eq!(package.read("lib/shared.g.dart"), shared);
}
