//! End-to-end tests for output ownership (spec 0001), run against a temporary Dart package.

use flint_build::builder::{BuildReport, build, clean};
use flint_build::config::Pubspec;
use flint_build::generators::flint_json::emitter::FlintJsonGenerator;
use flint_build::output;
use flint_build::registry::PluginRegistry;
use std::fs;
use std::path::PathBuf;
use std::time::{Duration, SystemTime};
use tempfile::TempDir;

const USER: &str = "part 'user.g.dart';

@JsonSerializable()
class User {
  final int id;
  User({required this.id});
}
";

const FOREIGN: &str = "// GENERATED CODE - DO NOT MODIFY BY HAND\n\npart of 'x.dart';\n\n// written by another generator\n";

struct Package {
    dir: TempDir,
}

impl Package {
    fn new(flint_yaml: &str) -> Self {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir(dir.path().join("lib")).unwrap();
        fs::write(dir.path().join("flint.yaml"), flint_yaml).unwrap();
        Package { dir }
    }

    fn json() -> Self {
        Self::new("plugins:\n  flint_json:\n")
    }

    fn path(&self, relative: &str) -> PathBuf {
        self.dir.path().join(relative)
    }

    fn write(&self, relative: &str, content: &str) {
        fs::write(self.path(relative), content).unwrap();
    }

    fn read(&self, relative: &str) -> String {
        fs::read_to_string(self.path(relative)).unwrap()
    }

    fn exists(&self, relative: &str) -> bool {
        self.path(relative).exists()
    }

    fn set_mtime(&self, relative: &str, seconds_after_epoch: u64) {
        let file = fs::File::options()
            .write(true)
            .open(self.path(relative))
            .unwrap();
        file.set_modified(SystemTime::UNIX_EPOCH + Duration::from_secs(seconds_after_epoch))
            .unwrap();
    }

    /// Makes an output look older than its source, so the mtime check can't skip it.
    fn age(&self, relative: &str) {
        self.set_mtime(relative, 1);
    }

    fn build(&self, force: bool) -> BuildReport {
        let mut registry = PluginRegistry::new();
        registry.register("flint_json", Box::new(FlintJsonGenerator));
        let pubspec: Pubspec = "name: app\n".parse().unwrap();
        build(self.dir.path(), &pubspec, force, &registry).unwrap()
    }
}

#[test]
fn test_writes_owned_output_for_annotated_source() {
    let package = Package::json();
    package.write("lib/user.dart", USER);

    let report = package.build(false);

    assert_eq!(report.written, vec![package.path("lib/user.g.dart")]);
    assert!(report.errors.is_empty() && report.warnings.is_empty());
    let generated = package.read("lib/user.g.dart");
    assert!(generated.contains("part of 'user.dart';"));
    assert!(generated.contains("_$UserFromJson"));
    assert!(output::is_owned(&package.path("lib/user.g.dart")).unwrap());
}

#[test]
fn test_clean_leaves_files_flint_did_not_write() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.build(false);
    package.write("lib/other.g.dart", FOREIGN);

    let report = clean(package.dir.path()).unwrap();

    assert_eq!(report.deleted, vec![package.path("lib/user.g.dart")]);
    assert_eq!(report.skipped, vec![package.path("lib/other.g.dart")]);
    assert!(!package.exists("lib/user.g.dart"));
    assert_eq!(package.read("lib/other.g.dart"), FOREIGN);
}

#[test]
fn test_unannotated_source_produces_nothing() {
    let package = Package::json();
    package.write(
        "lib/plain.dart",
        "class Plain {\n  final int a;\n  Plain(this.a);\n}\n",
    );
    package.write("lib/color.dart", "enum Color { red, green }\n");

    let report = package.build(false);

    assert!(report.written.is_empty());
    assert!(!package.exists("lib/plain.g.dart"));
    assert!(!package.exists("lib/color.g.dart"));
}

#[test]
fn test_missing_part_directive_warns_and_writes_nothing() {
    let package = Package::json();
    package.write("lib/user.dart", &USER.replace("part 'user.g.dart';\n", ""));

    let report = package.build(false);

    assert!(!package.exists("lib/user.g.dart"));
    assert_eq!(report.warnings.len(), 1);
    assert!(report.warnings[0].contains("part 'user.g.dart';"));
}

#[test]
fn test_unowned_output_is_only_overwritten_with_force() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.write("lib/user.g.dart", FOREIGN);

    let report = package.build(false);
    assert_eq!(report.errors.len(), 1);
    assert!(report.errors[0].contains("wasn't generated by Flint"));
    assert_eq!(package.read("lib/user.g.dart"), FOREIGN);

    let report = package.build(true);
    assert!(report.errors.is_empty());
    assert!(package.read("lib/user.g.dart").contains("_$UserFromJson"));
}

#[test]
fn test_legacy_flint_output_is_treated_as_owned() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.write(
        "lib/user.g.dart",
        "// GENERATED CODE - DO NOT MODIFY BY HAND\n\npart of 'user.dart';\n\n// JsonSerializableGenerator (Powered by Flint)\n",
    );
    package.age("lib/user.g.dart");

    let report = package.build(false);

    assert!(report.errors.is_empty());
    assert_eq!(report.written.len(), 1);
}

#[test]
fn test_plugins_share_one_file_in_config_order() {
    let package = Package::new(
        "plugins:\n  describe:\n    class_annotations: [\"@JsonSerializable\"]\n    template_path: describe.tera\n  flint_json:\n",
    );
    package.write(
        "describe.tera",
        "// GENERATED CODE - DO NOT MODIFY BY HAND\n\npart of '{{ filename }}';\n\n{% for class in classes %}// describes {{ class.name }}\n{% endfor %}",
    );
    package.write("lib/user.dart", USER);

    package.build(false);
    let first = package.read("lib/user.g.dart");
    for _ in 0..10 {
        package.build(true);
        assert_eq!(package.read("lib/user.g.dart"), first);
    }

    let describe = first.find("// describes User").unwrap();
    let json = first.find("_$UserFromJson").unwrap();
    assert!(describe < json, "sections must follow flint.yaml order");
    assert_eq!(first.matches("part of 'user.dart';").count(), 1);
    assert_eq!(first.matches("DO NOT MODIFY BY HAND").count(), 1);
}

#[test]
fn test_stale_owned_output_is_deleted() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.write("lib/gone.dart", &USER.replace("user.g.dart", "gone.g.dart"));
    package.build(false);
    package.write("lib/other.g.dart", FOREIGN);

    package.write("lib/user.dart", "part 'user.g.dart';\n\nclass User {}\n");
    package.age("lib/user.g.dart");
    fs::remove_file(package.path("lib/gone.dart")).unwrap();
    let report = package.build(false);

    assert_eq!(
        report.deleted,
        vec![
            package.path("lib/user.g.dart"),
            package.path("lib/gone.g.dart")
        ]
    );
    assert!(!package.exists("lib/user.g.dart"));
    assert!(!package.exists("lib/gone.g.dart"));
    assert!(package.exists("lib/other.g.dart"));
}

#[test]
fn test_unchanged_output_is_not_rewritten() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.build(false);

    let report = package.build(false);
    assert_eq!(report.up_to_date, 1);

    let report = package.build(true);
    assert_eq!(report.unchanged, 1);
    assert!(report.written.is_empty());
}

#[test]
fn test_config_change_regenerates_and_drops_removed_plugin() {
    let package = Package::new(
        "plugins:\n  flint_json:\n  describe:\n    class_annotations: [\"@JsonSerializable\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for class in classes %}// describes {{ class.name }}\n{% endfor %}",
    );
    package.write("lib/user.dart", USER);
    package.build(false);
    assert!(
        package
            .read("lib/user.g.dart")
            .contains("// describes User")
    );

    // Only flint.yaml is newer than the output; the source is older.
    package.write("flint.yaml", "plugins:\n  flint_json:\n");
    package.set_mtime("lib/user.dart", 1);
    package.set_mtime("lib/user.g.dart", 2);
    let report = package.build(false);

    assert_eq!(report.written, vec![package.path("lib/user.g.dart")]);
    let generated = package.read("lib/user.g.dart");
    assert!(!generated.contains("// describes User"));
    assert!(generated.contains("_$UserFromJson"));
}

#[test]
fn test_unchanged_output_gets_fresh_mtime_so_next_build_skips_it() {
    let package = Package::json();
    package.write("lib/user.dart", USER);
    package.build(false);
    package.age("lib/user.g.dart");

    let report = package.build(false);
    assert_eq!(report.unchanged, 1);

    let report = package.build(false);
    assert_eq!(report.up_to_date, 1);
}

#[test]
fn test_template_copied_from_old_builtin_gets_one_part_of() {
    let package = Package::new("plugins:\n  flint_json:\n    template_path: old.tera\n");
    package.write(
        "old.tera",
        "// GENERATED CODE - DO NOT MODIFY BY HAND\n// ignore_for_file: unnecessary_cast\n\npart of '{{ filename }}';\n\n{% for class in classes %}// {{ class.name }}\n{% endfor %}",
    );
    package.write("lib/user.dart", USER);

    package.build(false);

    let generated = package.read("lib/user.g.dart");
    assert_eq!(generated.matches("part of ").count(), 1);
    assert_eq!(generated.matches("DO NOT MODIFY BY HAND").count(), 1);
    assert!(generated.contains("// ignore_for_file: unnecessary_cast"));
}

fn package_with_template(template: Option<&str>) -> Package {
    let package = Package::new(
        "plugins:\n  flint_json:\n  custom:\n    class_annotations: [\"@JsonSerializable\"]\n    template_path: custom.tera\n",
    );
    if let Some(template) = template {
        package.write("custom.tera", template);
    }
    package.write("lib/user.dart", USER);
    package
}

#[test]
fn test_missing_template_is_an_error_and_other_plugins_still_run() {
    let package = Package::new(
        "plugins:\n  flint_json:\n  custom:\n    class_annotations: [\"@Describe\"]\n    template_path: custom.tera\n",
    );
    package.write("lib/user.dart", USER);
    package.write(
        "lib/described.dart",
        "part 'described.g.dart';\n\n@Describe()\nclass Described {}\n",
    );

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.errors[0].contains("Plugin 'custom'"));
    assert!(report.errors[0].contains("custom.tera"));
    // Files the broken plugin doesn't match are built as usual; the ones it matches are left alone.
    assert!(package.read("lib/user.g.dart").contains("_$UserFromJson"));
    assert!(!package.exists("lib/described.g.dart"));
    assert_eq!(report.blocked, 1);
}

#[test]
fn test_template_syntax_error_explains_where() {
    let package = package_with_template(Some("{% for c in classes %}{{ c.name }\n"));

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.errors[0].contains("Plugin 'custom'"));
    assert!(report.errors[0].contains("1:"), "{}", report.errors[0]);
}

#[test]
fn test_template_render_error_is_reported_per_file() {
    let package = package_with_template(Some("{{ nope }}\n"));

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.errors[0].contains("user.dart"));
    assert!(report.errors[0].contains("nope"), "{}", report.errors[0]);
    assert!(!package.exists("lib/user.g.dart"));
}

#[test]
fn test_broken_template_leaves_its_outputs_untouched() {
    let package = Package::new(
        "plugins:\n  flint_json:\n  describe:\n    class_annotations: [\"@Describe\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for class in classes %}// describes {{ class.name }}\n{% endfor %}",
    );
    // Only the describe plugin matches only.dart; both plugins match shared.dart.
    package.write(
        "lib/only.dart",
        "part 'only.g.dart';\n\n@Describe()\nclass Only {}\n",
    );
    package.write(
        "lib/shared.dart",
        &format!(
            "{}\n@Describe()\nclass Extra {{}}\n",
            USER.replace("user.g.dart", "shared.g.dart")
        ),
    );
    package.build(false);
    let only = package.read("lib/only.g.dart");
    let shared = package.read("lib/shared.g.dart");
    assert!(shared.contains("// describes Extra") && shared.contains("_$UserFromJson"));

    // A typo in the template while the sources are being edited: nothing the plugin touches may change.
    package.write(
        "describe.tera",
        "{% for class in classes %}{{ class.name }\n",
    );
    package.age("lib/only.g.dart");
    package.age("lib/shared.g.dart");
    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.deleted.is_empty(), "{:?}", report.deleted);
    assert_eq!(report.blocked, 2);
    assert_eq!(package.read("lib/only.g.dart"), only);
    assert_eq!(package.read("lib/shared.g.dart"), shared);
}

#[test]
fn test_unsupported_field_type_is_reported_with_its_line() {
    let package = Package::json();
    let source = USER.replace(
        "  final int id;\n",
        "  final int id;\n  final (int, String) pair;\n",
    );
    package.write("lib/user.dart", &source);

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(
        report.errors[0].contains("user.dart: line 6: field 'pair'"),
        "{}",
        report.errors[0]
    );
    assert!(!package.exists("lib/user.g.dart"));
}

#[test]
fn test_ambiguous_type_is_an_error_naming_both_files() {
    let package = Package::json();
    package.write("lib/a.dart", "class Shared {}\n");
    package.write("lib/b.dart", "class Shared {}\n");
    package.write(
        "lib/user.dart",
        &format!(
            "import 'a.dart';\nimport 'b.dart';\n{}",
            USER.replace(
                "  final int id;\n",
                "  final int id;\n  final Shared shared;\n"
            )
        ),
    );

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    let error = &report.errors[0];
    assert!(
        error.contains("line 8: field 'shared' of 'User'"),
        "{error}"
    );
    assert!(
        error.contains("declared in lib/a.dart and lib/b.dart"),
        "{error}"
    );
    assert!(!package.exists("lib/user.g.dart"));
}

#[test]
fn test_templates_see_resolved_types() {
    let package = Package::new(
        "plugins:\n  describe:\n    class_annotations: [\"@Describe\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for name, type in resolved_types %}// {{ name }}: {{ type.kind }} {{ type.file | default(value=\"-\") }}\n{% endfor %}",
    );
    std::fs::create_dir_all(package.path("lib/src")).unwrap();
    package.write("lib/src/color.dart", "enum Color { red }\n");
    package.write(
        "lib/model.dart",
        "import 'src/color.dart' as c;\nimport 'package:other/other.dart';\npart 'model.g.dart';\n\n@Describe()\nclass Model<T> {\n  final c.Color color;\n  final List<Money> money;\n  final T value;\n}\n",
    );

    package.build(false);

    let generated = package.read("lib/model.g.dart");
    assert!(generated.contains("// Money: unresolved -"), "{generated}");
    assert!(
        generated.contains("// c.Color: enum lib/src/color.dart"),
        "{generated}"
    );
    // Type parameters aren't looked up.
    assert!(!generated.contains("// T:"), "{generated}");
}

#[test]
fn test_type_arguments_of_generic_types_are_resolved() {
    let package = Package::new(
        "plugins:\n  describe:\n    class_annotations: [\"@Describe\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for name, type in resolved_types %}// {{ name }}: {{ type.kind }}\n{% endfor %}",
    );
    package.write(
        "lib/a.dart",
        "class Shared {}\nclass Page<T> {}\nclass User {}\n",
    );
    package.write("lib/b.dart", "class Shared {}\n");
    let model = "import 'a.dart';\npart 'model.g.dart';\n\n@Describe()\nclass Model {\n  final Page<User?> page;\n  final Map<String, Page<List<User>>> pages;\n}\n";
    package.write("lib/model.dart", model);

    package.build(false);
    let generated = package.read("lib/model.g.dart");
    assert!(generated.contains("// Page: class"), "{generated}");
    assert!(generated.contains("// User: class"), "{generated}");
    assert!(!generated.contains("Page<"), "{generated}");

    // An ambiguous name inside type arguments is still an error.
    package.write(
        "lib/model.dart",
        &model
            .replace("import 'a.dart';\n", "import 'a.dart';\nimport 'b.dart';\n")
            .replace("Page<User?> page", "Page<Shared> page"),
    );
    let report = package.build(false);
    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    assert!(report.errors[0].contains("declared in lib/a.dart and lib/b.dart"));
}

#[test]
fn test_output_depends_on_the_files_its_types_come_from() {
    let package = Package::new(
        "plugins:\n  describe:\n    class_annotations: [\"@Describe\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for name, type in resolved_types %}// {{ name }}: {{ type.kind }}\n{% endfor %}",
    );
    package.write("lib/color.dart", "enum Color { red }\n");
    package.write("lib/other.dart", "class Unrelated {}\n");
    package.write(
        "lib/model.dart",
        "import 'color.dart';\nimport 'other.dart';\npart 'model.g.dart';\n\n@Describe()\nclass Model {\n  final Color color;\n}\n",
    );
    package.build(false);
    assert!(package.read("lib/model.g.dart").contains("// Color: enum"));

    // Only color.dart changes; model.dart and its output are older.
    package.set_mtime("lib/model.dart", 1);
    package.set_mtime("lib/model.g.dart", 2);
    package.write("lib/color.dart", "class Color {}\n");
    let report = package.build(false);
    assert_eq!(report.written, vec![package.path("lib/model.g.dart")]);
    assert!(package.read("lib/model.g.dart").contains("// Color: class"));

    // A new ambiguity is reported even though model.dart itself didn't change.
    package.write("lib/other.dart", "class Color {}\n");
    let report = package.build(false);
    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
}

/// `lib/model.dart` with `imports`, and a `@JsonSerializable` class `Model` with one field.
fn model_with_field(imports: &str, field: &str) -> String {
    format!(
        "{imports}part 'model.g.dart';\n\n@JsonSerializable()\nclass Model {{\n  {field}\n  Model();\n  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);\n}}\n"
    )
}

#[test]
fn test_class_without_from_json_is_an_error() {
    let package = Package::json();
    package.write(
        "lib/address.dart",
        "class Address {\n  final String street;\n}\n",
    );
    let imports = "import 'address.dart';\n";
    package.write(
        "lib/model.dart",
        &model_with_field(imports, "final List<Address> addresses;"),
    );

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    let error = &report.errors[0];
    assert!(
        error.contains(
            "line 6: field 'addresses' of 'Model' has type 'List<Address>', and `Address` has no `fromJson` constructor. Add one,"
        ),
        "{error}"
    );
    assert!(!package.exists("lib/model.g.dart"));

    // `@JsonSerializable` alone isn't enough: the generated code calls `Address.fromJson`.
    package.write(
        "lib/address.dart",
        "@JsonSerializable()\nclass Address {}\n",
    );
    let report = package.build(true);
    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);

    package.write(
        "lib/address.dart",
        "class Address {\n  Address();\n  factory Address.fromJson(Map<String, dynamic> json) => Address();\n}\n",
    );
    let report = package.build(true);
    assert!(report.errors.is_empty(), "{:?}", report.errors);
    assert!(
        package
            .read("lib/model.g.dart")
            .contains("Address.fromJson(")
    );
}

#[test]
fn test_class_without_from_json_is_fine_when_no_conversion_needs_it() {
    let package = Package::json();
    package.write("lib/address.dart", "class Address {}\n");
    let imports = "import 'address.dart';\n";
    for field in [
        // Only toJson is generated.
        "final Address address;\n}\n@JsonSerializable(createFactory: false)\nclass Other {\n  final Address address;",
        "@JsonKey(fromJson: _read, toJson: _write)\n  final Address address;",
        "@JsonKey(includeFromJson: false)\n  final Address? address;",
        "@JsonKey(ignore: true)\n  final Address? address;",
    ] {
        let source = model_with_field(imports, field);
        let source = source.replace(
            "final Address address;\n}\n@JsonSerializable(createFactory: false)",
            "final int id;\n}\n@JsonSerializable(createFactory: false)",
        );
        package.write("lib/model.dart", &source);
        let report = package.build(true);
        assert!(report.errors.is_empty(), "{field}: {:?}", report.errors);
    }
}

#[test]
fn test_mixins_typedefs_and_extension_types_are_errors() {
    let package = Package::json();
    package.write(
        "lib/kinds.dart",
        "mixin Named {}\ntypedef Json = Map<String, dynamic>;\nextension type Id(int value) {}\n",
    );
    for (field, expected) in [
        ("final Named named;", "has type 'Named', which is a mixin"),
        ("final Json json;", "has type 'Json', which is a typedef"),
        (
            "final Id? id;",
            "has type 'Id?', which is an extension type",
        ),
    ] {
        package.write(
            "lib/model.dart",
            &model_with_field("import 'kinds.dart';\n", field),
        );
        let report = package.build(true);
        assert_eq!(report.errors.len(), 1, "{field}: {:?}", report.errors);
        let error = &report.errors[0];
        assert!(error.contains(expected), "{error}");
        assert!(error.contains("which Flint can't serialize yet. Use @JsonKey(fromJson: …, toJson: …) or a converter."), "{error}");
    }
}

#[test]
fn test_unknown_type_without_other_packages_is_an_error() {
    let package = Package::json();
    package.write(
        "lib/model.dart",
        &model_with_field(
            "import 'dart:typed_data';\nimport 'package:app/other.dart';\n",
            "final Money price;",
        ),
    );
    package.write("lib/other.dart", "class Unrelated {}\n");

    let report = package.build(false);

    assert_eq!(report.errors.len(), 1, "{:?}", report.errors);
    let error = &report.errors[0];
    assert!(
        error.contains("has type 'Money', which isn't declared in this package or anything it imports. Import it, list it in `external_types`"),
        "{error}"
    );

    // A converter doesn't need a generated conversion, so the name is never looked at.
    let package = Package::new("plugins:\n  flint_json:\n    converters: [\"@MoneyConverter\"]\n");
    package.write(
        "lib/model.dart",
        &model_with_field("", "@MoneyConverter()\n  final Money price;"),
    );
    let report = package.build(false);
    assert!(report.errors.is_empty(), "{:?}", report.errors);
}

#[test]
fn test_unknown_type_from_another_package_warns_once() {
    let package = Package::json();
    let imports = "import 'package:money/money.dart' as m;\nimport 'package:money/money.dart';\n";
    package.write(
        "lib/model.dart",
        &model_with_field(imports, "final Money price;"),
    );
    package.write(
        "lib/other.dart",
        &model_with_field(imports, "final List<Money> prices;")
            .replace("model.g.dart", "other.g.dart")
            .replace("Model", "Other"),
    );
    package.write(
        "lib/third.dart",
        &model_with_field(imports, "final m.Money price;")
            .replace("model.g.dart", "third.g.dart")
            .replace("Model", "Third"),
    );

    let report = package.build(false);

    assert!(report.errors.is_empty(), "{:?}", report.errors);
    assert_eq!(report.written.len(), 3);
    assert!(package.read("lib/model.g.dart").contains("Money.fromJson("));
    // One warning for `Money` and `m.Money`: the fix is the same.
    assert_eq!(
        report.warnings,
        vec![format!(
            "`Money` (used in {} and 2 other files) isn't declared in this package, so Flint assumed it's a class with `fromJson`/`toJson` from an imported package. If it is, add `Money` to `external_types` under the plugin in flint.yaml to silence this warning.",
            package.path("lib/model.dart").display()
        )]
    );

    // Listing the type confirms it, for prefixed uses too.
    package.write(
        "flint.yaml",
        "plugins:\n  flint_json:\n    external_types: [Money]\n",
    );
    let report = package.build(true);
    assert!(report.errors.is_empty(), "{:?}", report.errors);
    assert!(report.warnings.is_empty(), "{:?}", report.warnings);
    assert_eq!(report.unchanged, 3);
}

#[test]
fn test_external_types_also_cover_files_without_other_packages() {
    let package = Package::new("plugins:\n  flint_json:\n    external_types: [Money]\n");
    package.write(
        "lib/model.dart",
        &model_with_field("", "final Money price;"),
    );

    let report = package.build(false);

    assert!(report.errors.is_empty(), "{:?}", report.errors);
    assert!(report.warnings.is_empty(), "{:?}", report.warnings);
    assert!(package.read("lib/model.g.dart").contains("Money.fromJson("));
}

#[test]
fn test_editing_an_enum_in_another_file_regenerates_its_map() {
    let package = Package::json();
    fs::create_dir_all(package.path("lib/src")).unwrap();
    package.write("lib/src/color.dart", "enum Color { red }\n");
    package.write(
        "lib/model.dart",
        &model_with_field("import 'src/color.dart';\n", "final Color color;"),
    );
    package.build(false);
    assert!(
        package
            .read("lib/model.g.dart")
            .contains("Color.red: 'red'")
    );

    // Only color.dart changes; model.dart and its output are older.
    package.set_mtime("lib/model.dart", 1);
    package.set_mtime("lib/model.g.dart", 2);
    package.write("lib/src/color.dart", "enum Color { red, green }\n");
    let report = package.build(false);

    assert_eq!(report.written, vec![package.path("lib/model.g.dart")]);
    assert!(
        package
            .read("lib/model.g.dart")
            .contains("Color.green: 'green'")
    );
}

#[test]
fn test_templates_see_constructors_getters_and_field_flags() {
    let package = Package::new(
        "plugins:\n  describe:\n    class_annotations: [\"@Describe\"]\n    template_path: describe.tera\n",
    );
    package.write(
        "describe.tera",
        "{% for class in classes %}\
{% for f in class.fields %}// field {{ f.name }} late={{ f.is_late }} init={{ f.has_initializer }} private={{ f.is_private }}\n{% endfor %}\
{% for g in class.getters %}// getter {{ g.name }}\n{% endfor %}\
{% for c in class.constructors %}// constructor {{ c.name | default(value=\"(unnamed)\") }} factory={{ c.is_factory }}:\
{% for p in c.params %} {{ p.kind }}/{{ p.initializes }}/{{ p.name }}{% if p.required %}!{% endif %}{% if p.default %}={{ p.default }}{% endif %}{% endfor %}\n{% endfor %}\
{% endfor %}",
    );
    package.write(
        "lib/model.dart",
        "part 'model.g.dart';\n\n@Describe()\nclass Model {\n  final int a, _b;\n  late String c = 'x';\n  int get sum => a;\n  Model(this.a, [int b = 0]) : _b = b;\n  factory Model.named({required int a}) => Model(a);\n}\n",
    );

    let report = package.build(false);

    assert!(report.errors.is_empty(), "{:?}", report.errors);
    let generated = package.read("lib/model.g.dart");
    for line in [
        "// field a late=false init=false private=false",
        "// field _b late=false init=false private=true",
        "// field c late=true init=true private=false",
        "// getter sum",
        "// constructor (unnamed) factory=false: positional/this/a! optional_positional/plain/b=0",
        "// constructor named factory=true: named/plain/a!",
    ] {
        assert!(
            generated.contains(line),
            "missing {line:?} in:\n{generated}"
        );
    }
}
