use std::fs;

use anyhow::Result;
use clap::{Parser, Subcommand};

mod config;
mod discovery;
mod generators;
mod parser;
mod watcher;

#[derive(Parser)]
#[command(name = "flint")]
#[command(about = "⚡ A fast, native build_runner replacement", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Run a single build
    Build {
        /// Delete conflicting outputs before building
        #[arg(short, long, default_value_t = false)]
        delete_conflicting_outputs: bool,
    },
    /// Watch the filesystem and rebuild on changes
    Watch {
        /// Delete conflicting outputs before building
        #[arg(short, long, default_value_t = false)]
        delete_conflicting_outputs: bool,
    },
    /// Clean all generated files
    Clean,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match &cli.command {
        Commands::Build {
            delete_conflicting_outputs,
        } => run_build(*delete_conflicting_outputs)?,
        Commands::Watch {
            delete_conflicting_outputs,
        } => watcher::watch("lib", || run_build(*delete_conflicting_outputs))?,
        Commands::Clean => {
            println!("🧹 Cleaning generated files...");
        }
    }

    Ok(())
}

fn run_build(delete_conflicting_outputs: bool) -> Result<()> {
    let pubspec = config::Pubspec::load()?;
    println!(
        "🚀 Building project: {} (delete: {})",
        pubspec.name, delete_conflicting_outputs
    );

    let files = discovery::find_dart_files("lib");
    println!("🔍 Found {} .dart files to process", files.len());

    for path in &files {
        let classes = parser::parse_file(path)?;
        if !classes.is_empty() {
            let mut output_code = String::new();
            output_code.push_str("// Generated by flint\n\n");
            let filename = path.file_name().unwrap().to_str().unwrap();
            output_code.push_str(&format!("part of '{}';\n\n", filename));

            for class in &classes {
                let generated = generators::json_serializable::emitter::generate_json_code(class);
                output_code.push_str(&generated);
            }
            let output_path = path.with_extension("g.dart");
            fs::write(&output_path, output_code)?;
            println!("  ✅ Generated: {:?}", output_path);
        }
    }
    Ok(())
}
