use std::fs;

use anyhow::Result;
use clap::{Parser, Subcommand};

mod config;
mod discovery;
mod generators;
mod parser;
mod watcher;

#[derive(Parser)]
#[command(name = "flint")]
#[command(about = "⚡ A fast, native build_runner replacement", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Run a single build
    Build {
        /// Delete conflicting outputs before building
        #[arg(short, long, default_value_t = false)]
        delete_conflicting_outputs: bool,
    },
    /// Watch the filesystem and rebuild on changes
    Watch,
    /// Clean all generated files
    Clean,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match &cli.command {
        Commands::Build {
            delete_conflicting_outputs,
        } => {
            let pubspec = config::Pubspec::load()?;
            println!(
                "🚀 Building project: {} (delete: {})",
                pubspec.name, delete_conflicting_outputs
            );

            // Scan for files
            let files = discovery::find_dart_files("lib");
            println!("🔍 Found {} .dart files to process", files.len());

            for path in &files {
                let classes = parser::parse_file(path)?;
                if !classes.is_empty() {
                    let mut output_code = String::new();
                    output_code.push_str("// Generated by flint\n\n");
                    for class in &classes {
                        let filename = path.file_name().unwrap().to_str().unwrap();
                        output_code.push_str(&format!("part of '{}';\n\n", filename));

                        let generated =
                            generators::json_serializable::emitter::generate_json_code(class);
                        output_code.push_str(&generated);
                    }
                    // Determine output path: "lib/user.dart" -> "lib/user.g.dart"
                    let output_path = path.with_extension("g.dart");
                    fs::write(&output_path, output_code)?;
                    println!("  ✅ Generated: {:?}", output_path);
                }
            }
        }
        Commands::Watch => {
            println!("👀 Watching for changes...");
        }
        Commands::Clean => {
            println!("🧹 Cleaning generated files...");
        }
    }

    Ok(())
}
