use std::{fs, time::Instant};

use anyhow::Result;
use clap::{Parser, Subcommand};
use colored::Colorize;
use rayon::prelude::*;

mod config;
mod discovery;
mod generators;
mod parser;
mod watcher;

#[derive(Parser)]
#[command(name = "flint")]
#[command(about = "⚡ A fast, native build_runner replacement", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Run a single build
    Build {
        /// Delete conflicting outputs before building
        #[arg(short, long, default_value_t = false)]
        delete_conflicting_outputs: bool,
    },
    /// Watch the filesystem and rebuild on changes
    Watch {
        /// Delete conflicting outputs before building
        #[arg(short, long, default_value_t = false)]
        delete_conflicting_outputs: bool,
    },
    /// Clean all generated files
    Clean,
}

fn main() -> Result<()> {
    env_logger::init();
    let start = Instant::now();

    let cli = Cli::parse();

    match &cli.command {
        Commands::Build {
            delete_conflicting_outputs,
        } => run_build(*delete_conflicting_outputs)?,
        Commands::Watch {
            delete_conflicting_outputs,
        } => watcher::watch("lib", || run_build(*delete_conflicting_outputs))?,
        Commands::Clean => run_clean()?,
    }

    let duration = start.elapsed();
    println!(
        "\n{} {} in {:2.2?}",
        "✨".bold(),
        "Done".green().bold(),
        duration
    );
    Ok(())
}

fn run_build(delete_conflicting_outputs: bool) -> Result<()> {
    let pubspec = config::Pubspec::load()?;
    log::info!("Initializing build for package: {}", pubspec.name);
    println!(
        "{} {} {}",
        "🚀".bold(),
        "Building project:".green().bold(),
        pubspec.name.cyan().bold()
    );

    let files = discovery::find_dart_files("lib");
    log::debug!("Discovery found {} potential Dart files", files.len());
    println!("{} Found {} .dart files", "🔍".blue(), files.len());

    files.par_iter().try_for_each(|path| -> Result<()> {
        let output_path = path.with_extension("g.dart");
        if output_path.exists() && !delete_conflicting_outputs {
            let input_meta = fs::metadata(path)?;
            let output_meta = fs::metadata(&output_path)?;

            if input_meta.modified()? <= output_meta.modified()? {
                println!(
                    "  {} Skipping {}",
                    "⚠️".yellow(),
                    path.display().to_string().dimmed()
                );
                return Ok(());
            }
        }

        let classes = parser::parse_file(path)?;
        if !classes.is_empty() {
            let mut output_code = String::new();
            output_code.push_str("// Generated by flint\n\n");
            let filename = path.file_name().unwrap().to_str().unwrap();
            output_code.push_str(&format!("part of '{}';\n\n", filename));

            for class in &classes {
                let generated = generators::json_serializable::emitter::generate_json_code(class);
                output_code.push_str(&generated);
            }
            fs::write(&output_path, output_code)?;
            println!(
                "  {} Generated: {}",
                "✅".green(),
                output_path.display().to_string().bold()
            );
        }
        Ok(())
    })
}

fn run_clean() -> Result<()> {
    println!(
        "{} {}",
        "🧹".magenta(),
        "Cleaning generated files...".bold()
    );
    let files = discovery::find_generated_files("lib");
    files.par_iter().try_for_each(|path| -> Result<()> {
        fs::remove_file(path)?;
        println!(
            "  {} Deleted: {}",
            "🗑️".red().dimmed(),
            path.display().to_string().dimmed()
        );
        Ok(())
    })
}
